### ISSUE TITLE
Hey, mind if I use this?

### ISSUE THREAD

**Issue by ModalSeoul** [nat143/lastfm-data-exporter#1]
Star you star my project and took a quick look. This is exactly what I need(but have yet to write) for importing user data from last to WeebFM(temp name :+1: )

Would it be alright if I tossed this on a server and altered it a bit to use it as a service component?

**Comment by nat143** [comment]
Man, this is a huge coincidence. I just messaged you on Reddit a couple of minutes ago asking to help you testing the site.

You can use it. If you put up a list of projects you used, throw me in there.

Feel free to ask me if there's anything that's unclear.

**Comment by ModalSeoul** [comment]
Awesome! Thanks dude. Sorry for just seeing this comment, I had to take a day or so get some other work done. I'll end up writing a service component and daemonizing this by the end of the weekend. And I'll for sure toss up a credits list, linking to your github(if that's fine). On the site & readme of the project.
